(()=>{"use strict";
const KNOWLEDGE=[
{m:/mulai|masuk|workspace/i,t:"Mulai di SANGGAR",d:"Workspace adalah ruang kerja pribadi untuk mengubah tujuan menjadi journey, evidence, portfolio, Creative Passport, assessment, dan paket pengajuan.",n:"Jika baru mulai, buat Creator Journey atau Evidence pertama.",s:"Workspace adalah ruang kerja pribadi Anda di SANGGAR."},
{m:/academy|learning|belajar|skill/i,t:"Academy",d:"Academy membantu membangun kemampuan melalui learning path, praktik, proyek, dan evidence. Jalurnya mencakup 3D, AR, foto, video, desain, audio, digital product, dan jasa kreatif.",n:"Pilih kemampuan yang ingin dikuasai lalu ubah latihan menjadi proyek nyata.",s:"Academy membantu Anda membangun kemampuan melalui belajar, praktik, proyek, dan bukti."},
{m:/gallery|karya|portfolio/i,t:"Creator Gallery",d:"Gallery menampilkan karya dan menghubungkannya dengan portfolio serta Creative Passport sehingga karya dapat menjadi bukti profesional.",n:"Tampilkan karya terbaik setelah metadata, hak, provenance, dan kualitasnya siap.",s:"Creator Gallery membantu Anda menampilkan karya secara profesional."},
{m:/journey|tujuan|goal/i,t:"Creator Journey",d:"Journey menghubungkan tujuan, kebutuhan skill, learning, project, evidence, portfolio, marketplace match, dan outcome.",n:"Gunakan Journey untuk tujuan konkret seperti ingin menghasilkan uang dari 3D.",s:"Creator Journey menghubungkan tujuan Anda dengan skill, karya, peluang, dan hasil."},
{m:/identity|passport/i,t:"Identity & Creative Passport",d:"Identity menjadi fondasi identitas digital. Creative Passport dapat menghubungkan profil, skill, evidence, portfolio, dan kredensial.",n:"Bangun identitas dan bukti sebelum memperluas peluang.",s:"Identity dan Creative Passport menjadi fondasi identitas profesional Anda."},
{m:/data|evidence/i,t:"Data & Evidence",d:"Data menyimpan konteks perjalanan, sedangkan evidence menjadi bukti bahwa kemampuan atau output benar-benar pernah dikerjakan.",n:"Jadikan project dan hasil belajar sebagai evidence yang dapat diverifikasi.",s:"Evidence mengubah pekerjaan nyata menjadi bukti kemampuan."},
{m:/workflow|action|assessment|assess/i,t:"Workflow & Action",d:"Workflow menghubungkan pekerjaan nyata dari project, evidence, assessment, portfolio, hingga peluang.",n:"Jalankan action ketika input sudah cukup dan periksa hasil sebelum melanjutkan.",s:"Workflow menghubungkan proses kerja nyata dari project sampai peluang."},
{m:/intelligence|ai|companion|rekomendasi/i,t:"SANGGAR AI Intelligence",d:"AI SANGGAR dirancang untuk analisis, rekomendasi, pencocokan, evaluasi, dan bantuan kontekstual dengan policy checks, provenance, audit trail, dan human approval untuk risiko tinggi.",n:"Gunakan AI sebagai co-pilot; keputusan penting tetap berada pada manusia.",s:"AI SANGGAR membantu analisis dan rekomendasi dengan kendali manusia."},
{m:/market|economy|peluang|sell|jual/i,t:"Creative Economy",d:"SANGGAR menghubungkan karya dan kemampuan dengan marketplace, klien, proyek, monetisasi, dan pertumbuhan.",n:"Pastikan hak, metadata, kualitas, dan provenance siap sebelum diarahkan ke pasar.",s:"Creative Economy menghubungkan karya Anda dengan peluang ekonomi."},
{m:/governance|security|policy/i,t:"Governance",d:"Governance menjaga AI dan workflow tetap dapat dipercaya, dapat diaudit, dan memiliki batas kewenangan.",n:"Risiko tinggi tetap membutuhkan human approval.",s:"Governance menjaga AI tetap dapat dipercaya dan berada dalam kendali manusia."}
];
function itemFor(el,workspace){
 const raw=((el?.getAttribute("data-ai-context")||"")+" "+(el?.getAttribute("aria-label")||"")+" "+(el?.textContent||"")+" "+(el?.getAttribute("href")||"")).replace(/\s+/g," ").trim();
 for(const x of KNOWLEDGE)if(x.m.test(raw))return x;
 if(workspace&&/learning progress/i.test(raw))return {t:"Learning Progress",d:"Ini menunjukkan kemajuan learning Anda yang terhubung ke jalur pengembangan skill.",n:"Pilih satu modul lalu bawa hasil praktiknya menjadi evidence.",s:"Ini adalah progres learning Anda."};
 if(workspace&&/portfolio/i.test(raw))return {t:"Portfolio",d:"Portfolio mengemas karya dan evidence menjadi representasi profesional yang dapat ditampilkan.",n:"Pastikan karya utama memiliki evidence yang kuat.",s:"Portfolio mengemas karya dan bukti Anda."};
 if(workspace&&/passport/i.test(raw))return {t:"Creative Passport",d:"Creative Passport menghubungkan identitas, skill, evidence, portfolio, dan kredensial Anda.",n:"Gunakan passport sebagai identitas profesional yang dapat berkembang.",s:"Creative Passport menghubungkan identitas dan bukti profesional Anda."};
 if(workspace&&/submission package|paket pengajuan/i.test(raw))return {t:"Submission Package",d:"Paket pengajuan menyatukan metadata, provenance, hak, release, assessment, dan tujuan platform.",n:"Periksa blocker dan requirement sebelum pengajuan eksternal.",s:"Submission Package menyiapkan karya untuk pengajuan."};
 if(el?.tagName==="BUTTON")return {t:"Action",d:"Tombol ini menjalankan tindakan pada konteks halaman yang sedang Anda lihat.",n:"Pastikan input yang diperlukan sudah siap sebelum menjalankan action.",s:"Ini adalah action SANGGAR. Jalankan ketika Anda siap."};
 if(el?.tagName==="A")return {t:"Navigasi SANGGAR",d:"Tautan ini membawa Anda ke bagian lain dari ekosistem SANGGAR.",n:"Pilih bagian yang paling dekat dengan tujuan Anda.",s:"Tautan ini membawa Anda ke bagian lain di SANGGAR."};
 return null;
}
function mount(){
 const mode=document.body.getAttribute("data-sanggar-companion");
 if(!mode||document.getElementById("sanggar-ai-companion-v2"))return;
 const workspace=mode==="workspace";
 const root=document.createElement("aside");root.id="sanggar-ai-companion-v2";root.className="ai-companion";root.setAttribute("aria-label","SANGGAR AI Companion");
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n};
 const head=el("div","ai-companion-head");head.append(el("div","ai-avatar","S"));const identity=el("div");identity.append(el("strong",null,"SANGGAR AI Companion"),el("small",null,workspace?"Workspace co-pilot":"Context-aware guide"));head.append(identity);
 const mini=el("button","ai-minimize","−");mini.type="button";mini.setAttribute("aria-label","Minimalkan AI Companion");head.append(mini);
 const body=el("div","ai-companion-body");const label=el("span","ai-context-label",workspace?"WORKSPACE SIAP":"SIAP MEMBIMBING");const title=el("h3",null,workspace?"Saya siap membantu pekerjaan Anda.":"Halo, saya pendamping SANGGAR.");const para=el("p",null,workspace?"Saya membaca konteks workspace untuk menjelaskan action dan langkah berikutnya.":"Arahkan mouse atau keyboard ke bagian halaman. Saya akan menjelaskan fungsinya dan langkah berikutnya.");const nextBox=el("div","ai-next");nextBox.append(el("b",null,"Langkah berikutnya"),el("span",null,workspace?"Mulai dari tujuan atau action yang sedang Anda kerjakan.":"Mulai dari tujuan Anda, lalu saya bantu menemukan jalurnya."));body.append(label,title,para,nextBox);
 const actions=el("div","ai-companion-actions");const listen=el("button","ai-action","🔊 Dengarkan");listen.type="button";const stop=el("button","ai-action","■ Hentikan");stop.type="button";stop.hidden=true;const auto=el("button","ai-action","◉ Voice otomatis");auto.type="button";auto.setAttribute("aria-pressed","false");const help=el("button","ai-action","✦ Pandu saya");help.type="button";actions.append(listen,stop,auto,help);
 const status=el("div","ai-status","Companion aktif.");root.append(head,body,actions,status);document.body.append(root);
 let current={t:workspace?"Workspace co-pilot":"SANGGAR AI Companion",d:"Saya siap membantu.",n:"Mulai dari tujuan Anda.",s:"Saya siap membantu Anda di SANGGAR."},autoVoice=false,last=null,timer=null,idle=null;
 const speak=text=>{if(!("speechSynthesis"in window)){status.textContent="Voice tidak tersedia di browser ini.";return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="id-ID";u.rate=.96;u.pitch=1;const v=speechSynthesis.getVoices().find(x=>/^id[-_]/i.test(x.lang));if(v)u.voice=v;u.onstart=()=>{status.textContent="AI Companion sedang berbicara…";root.classList.add("is-speaking")};u.onend=()=>{status.textContent="Selesai berbicara.";root.classList.remove("is-speaking")};speechSynthesis.speak(u)};
 const render=x=>{if(!x)return;current=x;label.textContent="KONTEKS AKTIF";title.textContent=x.t;para.textContent=x.d;nextBox.querySelector("span").textContent=x.n;status.textContent="AI Companion memahami konteks: "+x.t;root.classList.add("is-active");if(autoVoice)speak(x.s||x.d)};
 const watch=target=>{if(!target||root.contains(target))return;const x=itemFor(target,workspace);if(!x)return;clearTimeout(timer);timer=setTimeout(()=>{if(target!==last){last=target;render(x)}},260)};
 const reset=()=>{clearTimeout(idle);idle=setTimeout(()=>render(workspace?{t:"Bimbingan Workspace",d:"Saya dapat membantu membaca konteks pekerjaan Anda. Sorot action, evidence, assessment, portfolio, passport, atau submission package untuk mendapatkan penjelasan.",n:"Jika bingung, tekan “Pandu saya” untuk alur yang direkomendasikan. ",s:"Saya dapat membantu membaca konteks pekerjaan Anda di Workspace."}:{t:"Bimbingan berikutnya",d:"Anda tidak perlu mengingat seluruh ekosistem. Mulai dari tujuan, lalu gunakan Journey, Academy, Evidence, Portfolio, dan Marketplace sesuai kebutuhan.",n:"Untuk jalur dari tujuan menuju peluang, buka Creator Journey.",s:"Anda tidak perlu mengingat semuanya. Mulai dari tujuan, lalu SANGGAR membantu membentuk jalurnya."}),11000)};
 document.addEventListener("mouseover",e=>{watch(e.target.closest("a,button,[data-ai-context],h1,h2,h3,article,.domain-card,.floating-chip,.ai-card"));reset()},{passive:true});
 document.addEventListener("focusin",e=>watch(e.target.closest("a,button,[data-ai-context],h1,h2,h3,article")),{passive:true});
 listen.addEventListener("click",()=>speak(current.s||current.d));stop.addEventListener("click",()=>{speechSynthesis?.cancel();root.classList.remove("is-speaking")});
 auto.addEventListener("click",()=>{autoVoice=!autoVoice;auto.textContent=autoVoice?"● Voice otomatis ON":"◉ Voice otomatis";auto.setAttribute("aria-pressed",String(autoVoice));status.textContent=autoVoice?"Konteks baru akan dibacakan otomatis.":"Voice otomatis dimatikan.";if(!autoVoice)speechSynthesis?.cancel()});
 help.addEventListener("click",()=>render(workspace?{t:"Pandu saya di Workspace",d:"Urutan kerja yang paling aman adalah: tetapkan tujuan → buat evidence → assessment → portfolio → Creative Passport → marketplace match → submission package.",n:"Mulai dari Creator Journey jika tujuan Anda belum jelas; jika karya sudah ada, mulai dari Evidence.",s:"Urutan kerja yang disarankan adalah tujuan, evidence, assessment, portfolio, passport, marketplace match, lalu submission package."}:{t:"Pandu saya",d:"Untuk belajar gunakan Academy. Untuk tujuan konkret gunakan Creator Journey. Untuk mengelola output dan bukti gunakan Workspace. Untuk menampilkan karya gunakan Gallery.",n:"Rekomendasi: Creator Journey → Learning → Project → Evidence → Portfolio → Marketplace Match.",s:"Untuk belajar gunakan Academy. Untuk tujuan konkret gunakan Creator Journey. Untuk mengelola karya gunakan Workspace."}));
 mini.addEventListener("click",()=>root.classList.toggle("is-collapsed"));reset();
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();
})();